AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: credential provider for actions-aws-assume-role

Parameters:
  ApiUrl:
    Type: String
    Default: https://api.github.com
    Description: The URL for GitHub API. You might need to configure it if you use GitHub Enterprise Server.

Resources:
  ProviderFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: assume-role/
      Handler: assume-role
      Runtime: provided.al2
      Architectures: [arm64]
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /assume-role
            Method: POST
      Role: !GetAtt ProviderFunctionRole.Arn
      Environment:
        Variables:
          GITHUB_API_URL: !Ref ApiUrl

  ProviderFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/aws-assume-role-permissions-boundary-us-east-1"
      MaxSessionDuration: 43200 # 43200 seconds = 12 hours
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
      Policies:
        - PolicyName: ProviderFunctionRolePolicy0
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - sts:TagSession
                Resource: "*"
